### ISSUE TITLE
Incorrect stuffing of container

### ISSUE THREAD

**Issue by JelmerDL** [treeDiM/MHBCrateLoadDesigner#15] opened 2021-03-04 14:14 UTC
In this case, crates should be able to fit next to eachother 

![image](https://user-images.githubusercontent.com/78344754/109976648-4e2b5e80-7cfc-11eb-923c-792c26716d51.png)

**Comment by fgasnier71** [comment] 2021-03-05 15:12
Is actually a duplicate of Issue #13

**Closed by fgasnier71** 2021-03-05 15:12 UTC
Labels: duplicate
